# ============================================================
# ShopNest UI Automation \u2014 Environment Configuration
# ============================================================

# Base URL
base.url=https://the-internet.herokuapp.com

# Browser (chrome | edge)
browser=chrome

# Headless mode (true | false) \u2014 set true for CI
headless=false

# Timeouts (seconds)
implicit.wait=0
explicit.wait=15
page.load.timeout=30

# Credentials \u2014 Login Page
valid.username=tomsmith
valid.password=SuperSecretPassword!

# Screenshot settings
screenshot.on.failure=true
screenshot.dir=test-output/screenshots

# Retry
retry.count=1

# Report
extent.report.dir=test-output/ExtentReports
extent.report.name=ShopNest_Automation_Report.html